import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
decorations = "full"

[window.padding]
x = 3
y = 3

[font]
size = 10

[font.normal]
style = "Retina,Regular"
# family = "FiraCode Nerd Font Mono"
family = "CaskaydiaMono Nerd Font Propo"

[font.bold]
style = "Bold"
# family = "FiraCode Nerd Font Mono"
family = "CaskaydiaMono Nerd Font Propo"

[font.italic]
style = "Light,Regular"
# family = "FiraCode Nerd Font Mono"
family = "CaskaydiaMono Nerd Font Propo"

[font.offset]
x = 0
y = 1
