import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
decorations = "full"

  [window.padding]
  x = 1
  y = 1

[font]
size = 12

  [font.normal]
  style = "Retina,Regular"
  family = "FiraCode Nerd Font Mono"

  [font.bold]
  style = "Bold"
  family = "FiraCode Nerd Font Mono"

  [font.italic]
  style = "Light,Regular"
  family = "FiraCode Nerd Font Mono"

  [font.offset]
  x = 0
  y = 1
